version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: lab5_nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  php:
    build: .  # ← ИЗМЕНЕНИЕ: используем наш Dockerfile
    container_name: lab5_php
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_NAME=lab5_db
      - DB_USER=lab5_user
      - DB_PASS=lab5_password

  mysql:
    image: mysql:8.0
    container_name: lab5_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lab5_db
      MYSQL_USER: lab5_user
      MYSQL_PASSWORD: lab5_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: